<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.0.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    <UserSecretsId>754bec78-468d-4deb-92fd-d2f851821139</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent-Framework-Demo.ApiService\Agent-Framework-Demo.ApiService.csproj" />
    <ProjectReference Include="..\Agent-Framework-Demo.Web\Agent-Framework-Demo.Web.csproj" />
    <ProjectReference Include="..\..\Demo001_JokerAgentDemo\Aspire\JokerAgentDemo.Web\JokerAgentDemo.Web.csproj" />
    <ProjectReference Include="..\..\Demo002_LightPluginDemo\Aspire\LightPluginDemo.Web\LightPluginDemo.Web.csproj" />
    <ProjectReference Include="..\..\Demo003_HumanInTheLoopDemo\Aspire\HumanInTheLoopDemo.Web\HumanInTheLoopDemo.Web.csproj" />
    <ProjectReference Include="..\..\Demo006_WorkflowSequentialDemo\Aspire\WorkflowSequentialDemo.Web\WorkflowSequentialDemo.Web.csproj" />
    <ProjectReference Include="..\..\Demo007_WorkflowConcurrentDemo\Aspire\WorkflowConcurrentDemo.Web\WorkflowConcurrentDemo.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.0.2" />
  </ItemGroup>

</Project>
